### PR TITLE
make sure all run dep are constrained within a major version

### PR DESCRIPTION
**Pull request by ickc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ickc** [comment]
I realize probably you want this happen at upstream first. c.f. https://github.com/sergiocorreia/panflute/pull/173

**Comment by ickc** [comment]
Upstream merged with the same set of constraints now. Again, if no objection, I'll merge in 24 hrs.

**Comment by beckermr** [comment]
No need to bump me on these and you should feel free to merge right away.

**Comment by kiwi0fruit** [comment]
I object to this as pypi panflute 2.0.5 doesn't have these.

**Comment by ickc** [comment]
Fair enough. Wait until next panflute release then

**Pull request closed without merging**
